### ISSUE TITLE
thanks for great resource. getting vimeo error,

### ISSUE THREAD

**Issue by badasscodr** [lem6ns/firerip#1]
![image info](https://i.imgur.com/eqcn8iU.png)

when i use one of vimeo videoId, in browser side, i shows me this ,
![](https://i.imgur.com/N8QDcRM.png)

how to fix this issue .

**Comment by lem6ns** [comment]
make sure everything is up to date, works fine for me

**Comment by badasscodr** [comment]
i also  installed dependencies
-> ffmpeg
-> yt-dlp 
-> python3

using ubuntu 22.04
using node 18.xx LTS 
using npm 8.x.x

what am I missing.

**Comment by lem6ns** [comment]
what version is ffmpeg and yt-dlp?
