### ISSUE TITLE
Merge video and audio file

### ISSUE THREAD

**Issue by 3xploiton3** [lem6ns/firerip#10]
can you make merge video and audio as single file?

![image](https://github.com/lem6ns/firerip/assets/19517680/3c532288-7dc2-407a-af10-6128d6c656f1)

**Comment by 3xploiton3** [comment]
![image](https://github.com/lem6ns/firerip/assets/19517680/96333fad-a6b9-409b-8ee3-cdbea5016b49)

**Comment by lem6ns** [comment]
should be merged automatically by ffmpeg
