### ISSUE TITLE
Error when Input node index.js

### ISSUE THREAD

**Issue by JohanChungus** [lem6ns/firerip#6]
audited 80 packages in 0.939s 7 packages are looking for funding run `npm fund` for details found 0 vulnerabilities /content/firerip/index.js:1 import getCourses from "./util/getCourses.js"; ^^^^^^^^^^ SyntaxError: Unexpected identifier at Module._compile (internal/modules/cjs/loader.js:723:23) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Function.Module.runMain (internal/modules/cjs/loader.js:831:12) at startup (internal/bootstrap/node.js:283:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by lem6ns** [comment]
works on my machine:tm:

**please do not create issues like this**, use latest node version
